#! /bin/bash

echo ' '
read -p 'Would you like to clear the previous map database? (y/n): ' ansinput

if [ “$ansinput” = “y” ]
then
 printf '\n Map deleted \n'
 rm -f ~/.ros/rtabmap.db

elif [ “$ansinput” = “n” ]
then
 printf '\n Map kept \n'

else
 echo 'Warning: Not an acceptable option. Choose (y/n).
         '
fi

echo ' '

read -p 'Enter target world destination or d for default: ' input_choice

if [ “$input_choice” = “d” ]
then
 x-terminal-emulator -x roslaunch rtab_shelly world.launch world_file:=/home/nvidia/catkin_ws/src/rtab_shelly/worlds/kitchen_dining.world 2>/dev/null &

else
 x-terminal-emulator -x roslaunch rtab_shelly world.launch world_file:=home/nvidia/catkin_ws/src/rtab_shelly/worlds/rw.world 2>/dev/null &
fi

sleep 3 &&

x-terminal-emulator -x roslaunch rtab_shelly teleop.launch 2>/dev/null &

sleep 3 &&

echo ' '
read -p 'Press any key to continue to mapping... ' -n1 -s

x-terminal-emulator -x roslaunch rtab_shelly mapping.launch simulation:=true 2>/dev/null &
sleep 3 &&
x-terminal-emulator -e roslaunch rtab_shelly rviz.launch 2>/dev/null

echo ' '
echo 'Script Completed'
echo ' '
